// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFN_v9u7I7i1_IgPyGYk4e-yvfnhRfwkk',
    appId: '1:1958939954:web:dc46dbe1141b39ce495b2b',
    messagingSenderId: '1958939954',
    projectId: 'app-stock-1f5cb',
    authDomain: 'app-stock-1f5cb.firebaseapp.com',
    storageBucket: 'app-stock-1f5cb.firebasestorage.app',
    measurementId: 'G-4TJ6V9L2Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6F0Nt8MgTwTbsVZUFQvlAce8eFZ8DPNw',
    appId: '1:1958939954:android:fa404dc5677b40cc495b2b',
    messagingSenderId: '1958939954',
    projectId: 'app-stock-1f5cb',
    storageBucket: 'app-stock-1f5cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCThzUW09HkkH6ruAI789azzK6BMHgjFgA',
    appId: '1:1958939954:ios:af314eff333866e0495b2b',
    messagingSenderId: '1958939954',
    projectId: 'app-stock-1f5cb',
    storageBucket: 'app-stock-1f5cb.firebasestorage.app',
    iosBundleId: 'com.example.stock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCThzUW09HkkH6ruAI789azzK6BMHgjFgA',
    appId: '1:1958939954:ios:af314eff333866e0495b2b',
    messagingSenderId: '1958939954',
    projectId: 'app-stock-1f5cb',
    storageBucket: 'app-stock-1f5cb.firebasestorage.app',
    iosBundleId: 'com.example.stock',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFN_v9u7I7i1_IgPyGYk4e-yvfnhRfwkk',
    appId: '1:1958939954:web:2c287f98c8c47d7a495b2b',
    messagingSenderId: '1958939954',
    projectId: 'app-stock-1f5cb',
    authDomain: 'app-stock-1f5cb.firebaseapp.com',
    storageBucket: 'app-stock-1f5cb.firebasestorage.app',
    measurementId: 'G-V52MFNL82H',
  );

}