// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7eYij11J8OMa_0IX4X6KaEBCqntQQFDM',
    appId: '1:39483935865:web:a49f94c4677cc487c298a8',
    messagingSenderId: '39483935865',
    projectId: 'stockapp-3cebb',
    authDomain: 'stockapp-3cebb.firebaseapp.com',
    storageBucket: 'stockapp-3cebb.firebasestorage.app',
    measurementId: 'G-4TJ6V9L2Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7eYij11J8OMa_0IX4X6KaEBCqntQQFDM',
    appId: '1:39483935865:android:a49f94c4677cc487c298a8',
    messagingSenderId: '39483935865',
    projectId: 'stockapp-3cebb',
    storageBucket: 'stockapp-3cebb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7eYij11J8OMa_0IX4X6KaEBCqntQQFDM',
    appId: '1:39483935865:ios:af314eff333866e0495b2b',
    messagingSenderId: '39483935865',
    projectId: 'stockapp-3cebb',
    storageBucket: 'stockapp-3cebb.firebasestorage.app',
    iosBundleId: 'com.example.stock.gnnproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7eYij11J8OMa_0IX4X6KaEBCqntQQFDM',
    appId: '1:39483935865:ios:af314eff333866e0495b2b',
    messagingSenderId: '39483935865',
    projectId: 'stockapp-3cebb',
    storageBucket: 'stockapp-3cebb.firebasestorage.app',
    iosBundleId: 'com.example.stock.gnnproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7eYij11J8OMa_0IX4X6KaEBCqntQQFDM',
    appId: '1:39483935865:web:a49f94c4677cc487c298a8',
    messagingSenderId: '39483935865',
    projectId: 'stockapp-3cebb',
    authDomain: 'stockapp-3cebb.firebaseapp.com',
    storageBucket: 'stockapp-3cebb.firebasestorage.app',
    measurementId: 'G-V52MFNL82H',
  );

}